name: Format Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: 1.8.3
    - name: Run Biome
      run: biome ci .
