name: Publish Any Commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      # Docs: https://github.com/stackblitz-labs/pkg.pr.new
      - run: bunx pkg-pr-new publish --comment=update './packages/*' --packageManager=bun
